### ISSUE TITLE
Bobylev's Big "RKPD2 Bug" Checklist

### ISSUE THREAD

**Issue by TrashboxBobylev** [Zrp200/rkpd2#12]
- [x] #16
- [x] #17 
- [x] #18 
- [x] #20
- [x] #25 
- [x] #26
# Crashes
- [ ] #28

# Meta
- [x] The "new" item window behavior is not compatible with Blacksmith's smith (_reported on August 24th_)

# Talents

- [x] #27

## t2s
- [x] Shield Battery effect can be triggered without investing into actual talent (usually to minimal results) (_reported on October 13th_)
- [x] Inscribed Stealth empowered invisibility duration is 10/20 turns, instead of implied description's 12/18 turns (_reported on July 12th_)

## t3s
- [x] Empowered Strike has no effect in both Battlemage and Rat King variations (_reported on August 29th_)

- [x] Projectile Momentum buffs throwing weapons regardless of momentum being actually active (_reported on December 17th_)

- [x] Excess Charge grants 0.67/1.34/2 shielding per charge, rather than 1/2/3 shielding per charge from talent's description (_reported on July 11th_)
- [x] Soul Siphon's wand benefit doesn't seem to be present (_reported on July 19th and August 9th, somehow is fixed in RKA_)
- [x] Necromancer's Minions procs 3x rarer, than it should be (_reported on January 15th 2025_)

# Duelist
- [x] #22 
- [x] #23

# #19
- [x] Inevitability's Hold Fast variation gives no armor at all (_reported on August 1st_)
- [x] Hold Fast has its actual armor value unchanged from Shattered (_reported on August 1st_)

# Exploits
- [x] #21

**Comment by Zrp200** [comment]
I'm working through these

**Comment by Zrp200** [comment]
Soul siphon appears to work here, too, idk what's up with that.
